/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ex001;

/**
 *
 * @author brant
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTxt = new javax.swing.JLabel();
        jLabelAkinator = new javax.swing.JLabel();
        jLabelBallon = new javax.swing.JLabel();
        jNum = new javax.swing.JSpinner();
        jButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTxt.setText("<html>Guess a number<br>from 0 to 5!");
        jLabelTxt.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        getContentPane().add(jLabelTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 110, 70));

        jLabelAkinator.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelAkinator.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ex001/akinator.png"))); // NOI18N
        getContentPane().add(jLabelAkinator, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 30, 111, -1));

        jLabelBallon.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabelBallon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ex001/balao.png"))); // NOI18N
        jLabelBallon.setToolTipText("");
        jLabelBallon.setOpaque(true);
        jLabelBallon.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        getContentPane().add(jLabelBallon, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, 130, 120));
        getContentPane().add(jNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 80, -1));

        jButton.setText("Guess");
        jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonActionPerformed(evt);
            }
        });
        getContentPane().add(jButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonActionPerformed
        int num = (int) (Math.random() * 6);
        System.out.println(num);
        int num2 = (int) jNum.getValue();
        if(num == num2){
            jLabelTxt.setText("You Win!");
        } else {
            jLabelTxt.setText("<html>No, the number<br>was: " + num);
        }
    }//GEN-LAST:event_jButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton;
    private javax.swing.JLabel jLabelAkinator;
    private javax.swing.JLabel jLabelBallon;
    private javax.swing.JLabel jLabelTxt;
    private javax.swing.JSpinner jNum;
    // End of variables declaration//GEN-END:variables
}
